project_id = "chmhbrcugswwmpqzhugs"

[functions.admin-users]
verify_jwt = false

[functions.bootstrap-admin]
verify_jwt = false

[functions.process-boleto]
verify_jwt = false

[functions.import-card-statement]
verify_jwt = false

[functions.scan-order]
verify_jwt = false

[functions.sign-delivery-receipt]
verify_jwt = false

[functions.manage-evolution-instance]
verify_jwt = false

[functions.webhook-evolution]
verify_jwt = false

[functions.send-message]
verify_jwt = false
