// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://chmhbrcugswwmpqzhugs.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImNobWhicmN1Z3N3d21wcXpodWdzIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NjA4MzE1MDgsImV4cCI6MjA3NjQwNzUwOH0.fRG6m5DVCYCkG8f0RNQJ9bLYGlcPiInQtZz1lBrSpGU";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});